VALID_REFLEXSIVE_CLASS_NAME = 'Reflexsive'
VALID_REFLEXSIVE_MODULE_PATHS = [
    f'reflexsive.{VALID_REFLEXSIVE_CLASS_NAME}',
    f'reflexsive.core.{VALID_REFLEXSIVE_CLASS_NAME}',
]

VALID_REFLEXSIVEMETA_CLASS_NAME = 'ReflexsiveMeta'
VALID_REFLEXSIVEMETA_MODULE_PATHS = [
    f'reflexsive.core.{VALID_REFLEXSIVEMETA_CLASS_NAME}',
]
